package api

import (
	"time"

	"github.com/liut/morign/pkg/services/llm"
	"github.com/liut/morign/pkg/utils/words"
)

const (
	historyLimitToken = 50 * 1024
	esDone            = "[DONE]"

	dftSystemMsg = "You are a helpful assistant. If you cannot find relevant information in the provided context to answer the user's question, please honestly state that you don't know rather than making up an answer."
	dftToolsMsg  = "You will select the appropriate tool based on the user's question and call the tool to solve the problem. If the tool returns no relevant information, honestly state that you don't know rather than making up an answer. If the tool requires parameters, you must extract them from the user's question. Note that it is important to clearly distinguish between read and write operations. If a write operation is required by the tool, it must be explicitly stated in the user's question for writing purposes (such as adding, creating, appending, modifying, etc.), and all necessary parameters for the tool must be included in the user's question before calling; otherwise, treat it as a regular read operation or Q&A."
	welcomeText  = "Hello, I am your virtual assistant. How can I help you?"
)

func thisMoment() string {
	return "Current Date: " + time.Now().Format("2006-01-02 15:04")
}

type ChatRequest struct {
	Prompt          string `json:"prompt"`
	ConversationID  string `json:"csid"`
	ParentMessageID string `json:"pmid"` // TODO: rename to PreviousMessageID
	Regenerate      bool   `json:"regen"`
	Stream          bool   `json:"stream"`

	MCPs []string `json:"mcps,omitempty"`

	// deprecated: for github.com/Chanzhaoyu/chatgpt-web only
	Options struct {
		ConversationId string `json:"conversationId,omitempty"`
	} `json:"options,omitempty"`
}

func (z *ChatRequest) GetConversionID() string {
	if z.ConversationID != "" {
		return z.ConversationID
	}
	if z.Options.ConversationId != "" {
		return z.Options.ConversationId
	}
	return ""
}

type ChatMessage struct {
	ID    string `json:"id,omitempty"`
	Delta string `json:"delta,omitempty"`
	Text  string `json:"text,omitempty"`
	Role  string `json:"role,omitempty"`
	Name  string `json:"name,omitempty"`

	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []map[string]any `json:"tool_calls,omitempty"`

	// For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.
	ToolCallID string `json:"tool_call_id,omitempty"`

	FinishReason string `json:"finishReason,omitempty"`

	ConversationID string `json:"csid,omitempty"`

	Title string `json:"title,omitempty"`
}

type ChatResponse struct {
	answer    string
	toolCalls []llm.ToolCall
	usage     *llm.Usage
	finish    llm.FinishReason
}

func cutTxt(s string, n int, opts ...string) string {
	return words.TakeHead(s, n, opts...)
}
