package api

import (
	"time"

	"github.com/liut/morign/pkg/services/llm"
	"github.com/liut/morign/pkg/utils/words"
)

const (
	historyLimitToken = 50 * 1024
	esDone            = "[DONE]"

	dftSystemMsg = "You are a helpful assistant. If you cannot find relevant information in the provided context to answer the user's question, please honestly state that you don't know rather than making up an answer."
	dftToolsMsg  = "You will select the appropriate tool based on the user's question and call the tool to solve the problem. If the tool returns no relevant information, honestly state that you don't know rather than making up an answer. If the tool requires parameters, you must extract them from the user's question. Note that it is important to clearly distinguish between read and write operations. If a write operation is required by the tool, it must be explicitly stated in the user's question for writing purposes (such as adding, creating, appending, modifying, etc.), and all necessary parameters for the tool must be included in the user's question before calling; otherwise, treat it as a regular read operation or Q&A."
	welcomeText  = "Hello, I am your virtual assistant. How can I help you?"
)

func thisMoment() string {
	now := time.Now()
	hour := now.Hour()

	// 十二时辰顺序：子丑寅卯辰巳午未申酉戌亥
	var shichen string
	switch {
	case hour >= 23 || hour < 1:
		shichen = "子时"
	case hour >= 1 && hour < 3:
		shichen = "丑时"
	case hour >= 3 && hour < 5:
		shichen = "寅时"
	case hour >= 5 && hour < 7:
		shichen = "卯时"
	case hour >= 7 && hour < 9:
		shichen = "辰时"
	case hour >= 9 && hour < 11:
		shichen = "巳时"
	case hour >= 11 && hour < 13:
		shichen = "午时"
	case hour >= 13 && hour < 15:
		shichen = "未时"
	case hour >= 15 && hour < 17:
		shichen = "申时"
	case hour >= 17 && hour < 19:
		shichen = "酉时"
	case hour >= 19 && hour < 21:
		shichen = "戌时"
	case hour >= 21 && hour < 23:
		shichen = "亥时"
	}

	return "当前时辰: " + now.Format("2006-01-02") + " " + shichen
}

type ChatRequest struct {
	Prompt          string `json:"prompt"`
	ConversationID  string `json:"csid"`
	ParentMessageID string `json:"pmid"` // TODO: rename to PreviousMessageID
	Regenerate      bool   `json:"regen"`
	Stream          bool   `json:"stream"`

	MCPs []string `json:"mcps,omitempty"`

	// deprecated: for github.com/Chanzhaoyu/chatgpt-web only
	Options struct {
		ConversationId string `json:"conversationId,omitempty"`
	} `json:"options,omitempty"`
}

func (z *ChatRequest) GetConversionID() string {
	if z.ConversationID != "" {
		return z.ConversationID
	}
	if z.Options.ConversationId != "" {
		return z.Options.ConversationId
	}
	return ""
}

// for response to client
type ChatMessage struct {
	ID    string `json:"id,omitempty"`
	Delta string `json:"delta,omitempty"`
	Text  string `json:"text,omitempty"`
	Think string `json:"think,omitempty"`
	Role  string `json:"role,omitempty"`
	Name  string `json:"name,omitempty"`

	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []map[string]any `json:"tool_calls,omitempty"`

	// For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.
	ToolCallID string `json:"tool_call_id,omitempty"`

	FinishReason string `json:"finishReason,omitempty"`

	ConversationID string `json:"csid,omitempty"`

	Title string `json:"title,omitempty"`
}

// wrap response from llm
type chatResponse struct {
	answer    string
	toolCalls []llm.ToolCall
	usage     *llm.Usage
	finish    llm.FinishReason

	model    string
	llmResID string
}

func cutTxt(s string, n int, opts ...string) string {
	return words.TakeHead(s, n, opts...)
}
