package api

const (
	historyLimitToken = 50 * 1024
	esDone            = "[DONE]"
	welcomeText  = "Hello, I am your virtual assistant. How can I help you?"
)

type ChatRequest struct {
	Prompt          string `json:"prompt"`
	ConversationID  string `json:"csid"`
	ParentMessageID string `json:"pmid"` // TODO: rename to PreviousMessageID
	Regenerate      bool   `json:"regen"`
	Stream          bool   `json:"stream"`

	MCPs []string `json:"mcps,omitempty"`
	// 技能清单范围：仅圈定注入 system prompt 的技能元数据
	Skills []string `json:"skills,omitempty"`

	// deprecated: for github.com/Chanzhaoyu/chatgpt-web only
	Options struct {
		ConversationId string `json:"conversationId,omitempty"`
	} `json:"options,omitempty"`
}

func (z *ChatRequest) GetConversionID() string {
	if z.ConversationID != "" {
		return z.ConversationID
	}
	if z.Options.ConversationId != "" {
		return z.Options.ConversationId
	}
	return ""
}

// for response to client
type ChatMessage struct {
	ID    string `json:"id,omitempty"`
	Delta string `json:"delta,omitempty"`
	Text  string `json:"text,omitempty"`
	Think string `json:"think,omitempty"`
	Role  string `json:"role,omitempty"`
	Name  string `json:"name,omitempty"`

	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []map[string]any `json:"tool_calls,omitempty"`

	// For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.
	ToolCallID string `json:"tool_call_id,omitempty"`

	FinishReason string `json:"finishReason,omitempty"`

	ConversationID string `json:"csid,omitempty"`

	Title string `json:"title,omitempty"`
}
